import { NextRequest, NextResponse } from "next/server";

interface NFTMetadataAttribute {
  trait_type: string;
  value: string;
}

interface NFTMetadata {
  name: string;
  description: string;
  image: string;
  attributes?: NFTMetadataAttribute[];
}

interface PinataResponse {
  IpfsHash: string;
}

async function pinToPinata(blob: Blob | string, filename: string, isJson = false): Promise<string> {
  const apiKey = process.env.PINATA_API_KEY;
  const secretKey = process.env.PINATA_SECRET_KEY;

  if (!apiKey || !secretKey) {
    throw new Error("Pinata API credentials not configured");
  }

  const formData = new FormData();

  if (isJson && typeof blob === "string") {
    const jsonBlob = new Blob([blob], { type: "application/json" });
    formData.append("file", jsonBlob, filename);
  } else if (blob instanceof Blob) {
    formData.append("file", blob, filename);
  } else {
    throw new Error("Invalid blob type");
  }

  formData.append(
    "pinataMetadata",
    JSON.stringify({ name: filename })
  );

  const res = await fetch("https://api.pinata.cloud/pinning/pinFileToIPFS", {
    method: "POST",
    headers: {
      pinata_api_key: apiKey,
      pinata_secret_api_key: secretKey,
    },
    body: formData,
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Pinata upload failed: ${errText}`);
  }

  const data = await res.json() as PinataResponse;
  return data.IpfsHash;
}

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const name = formData.get("name") as string;
    const description = formData.get("description") as string;
    const imageFile = formData.get("image") as File | null;
    const imageUrl = formData.get("imageUrl") as string | null;
    const prompt = formData.get("prompt") as string | null;
    const style = formData.get("style") as string | null;

    if (!name) {
      return NextResponse.json({ error: "name is required" }, { status: 400 });
    }

    let imageCid: string;

    if (imageFile) {
      // Upload image file to IPFS
      imageCid = await pinToPinata(imageFile, `${name}.png`);
    } else if (imageUrl) {
      // Fetch image from URL and upload to IPFS
      const imgRes = await fetch(imageUrl);
      if (!imgRes.ok) throw new Error("Failed to fetch image from URL");
      const imgBlob = await imgRes.blob();
      imageCid = await pinToPinata(imgBlob, `${name}.png`);
    } else {
      return NextResponse.json(
        { error: "Either image file or imageUrl is required" },
        { status: 400 }
      );
    }

    const imageIpfsUrl = `ipfs://${imageCid}`;

    // Build ERC721 metadata
    const attributes: NFTMetadataAttribute[] = [];
    if (prompt) attributes.push({ trait_type: "AI Prompt", value: prompt });
    if (style) attributes.push({ trait_type: "Art Style", value: style });
    attributes.push({ trait_type: "Generated By", value: "AI NFT Studio" });

    const metadata: NFTMetadata = {
      name,
      description: description || "",
      image: imageIpfsUrl,
      attributes,
    };

    const metadataJson = JSON.stringify(metadata, null, 2);
    const metadataCid = await pinToPinata(metadataJson, `${name}-metadata.json`, true);
    const tokenURI = `ipfs://${metadataCid}`;

    return NextResponse.json({ tokenURI, imageCid, metadataCid });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
